version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - 5432:5432
  cache:
    image: umudik/fookie-cache
    env_file: .env 
    ports:
      - 2626:2626